export const items = [
  {
    id: 1,
    title: "Apple iPhone 12",
    category: "Electronics",
    price: 849,
    img: "https://m.media-amazon.com/images/I/71fVoqRC0wL.jpg",
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas ad error delectus voluptate optio, earum odio ducimus explicabo recusandae magnam hic, debitis vero impedit natus. Quod enim eaque, adipisci, sequi harum magnam provident dignissimos id voluptatum officia debitis corporis iusto animi magni rem quo quidem qui perferendis quibusdam beatae.`,
    amount: 1,
  },
  {
    id: 2,
    title: "Sony Playstation PS4",
    category: "Video Games",
    price: 499,
    img: "https://m.media-amazon.com/images/I/61n-yWHcmSS._AC_SL1500_.jpg",
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas ad error delectus voluptate optio, earum odio ducimus explicabo recusandae magnam hic, debitis vero impedit natus. Quod enim eaque, adipisci, sequi harum magnam provident dignissimos id voluptatum officia debitis corporis iusto animi magni rem quo quidem qui perferendis quibusdam beatae.`,
    amount: 1,
  },
  {
    id: 3,
    title: `Dell XPS 15.6"`,
    category: "Electronics",
    price: 2194,
    img: "https://m.media-amazon.com/images/I/81rpUXwWl8L._AC_SL1500_.jpg",
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas ad error delectus voluptate optio, earum odio ducimus explicabo recusandae magnam hic, debitis vero impedit natus. Quod enim eaque, adipisci, sequi harum magnam provident dignissimos id voluptatum officia debitis corporis iusto animi magni rem quo quidem qui perferendis quibusdam beatae.`,
    amount: 1,
  },
  {
    id: 4,
    title: "Dove Body Wash",
    category: "Beauty",
    price: 8,
    img: "https://m.media-amazon.com/images/I/71NbfFpRvzL._AC_SL1500_.jpg",
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas ad error delectus voluptate optio, earum odio ducimus explicabo recusandae magnam hic, debitis vero impedit natus. Quod enim eaque, adipisci, sequi harum magnam provident dignissimos id voluptatum officia debitis corporis iusto animi magni rem quo quidem qui perferendis quibusdam beatae.`,
    amount: 1,
  },
];
