export const items = [
  {
    id: 1,
    title: "Fender American Pro II",
    category: "SSS",
    price: 849,
    img: "https://cdn.shoplightspeed.com/shops/647465/files/36433092/fender-fender-player-stratocaster-mn-sunburst.jpg",
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas ad error delectus voluptate optio, earum odio ducimus explicabo recusandae magnam hic, debitis vero impedit natus. Quod enim eaque, adipisci, sequi harum magnam provident dignissimos id voluptatum officia debitis corporis iusto animi magni rem quo quidem qui perferendis quibusdam beatae.`,
    amount: 1,
  },
  {
    id: 2,
    title: "Gibson Les Paul",
    category: "HH",
    price: 499,
    img: "https://d1aeri3ty3izns.cloudfront.net/media/48/480824/600/preview.jpg",
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas ad error delectus voluptate optio, earum odio ducimus explicabo recusandae magnam hic, debitis vero impedit natus. Quod enim eaque, adipisci, sequi harum magnam provident dignissimos id voluptatum officia debitis corporis iusto animi magni rem quo quidem qui perferendis quibusdam beatae.`,
    amount: 1,
  },
  {
    id: 3,
    title: `Ibanez AZ"`,
    category: "HH",
    price: 2194,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyGbHkVibbN81TcwXcQymKN0MUXg2UP4GgAw&usqp=CAU",
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas ad error delectus voluptate optio, earum odio ducimus explicabo recusandae magnam hic, debitis vero impedit natus. Quod enim eaque, adipisci, sequi harum magnam provident dignissimos id voluptatum officia debitis corporis iusto animi magni rem quo quidem qui perferendis quibusdam beatae.`,
    amount: 1,
  },
  {
    id: 4,
    title: "Fender Telecaster",
    category: "SS",
    price: 500,
    img: "https://sirclocdn.com/nafiriguitar/products/_220225132425_Antique%20Silverburst%20Sample%201%20-%20Copy_full.JPG",
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas ad error delectus voluptate optio, earum odio ducimus explicabo recusandae magnam hic, debitis vero impedit natus. Quod enim eaque, adipisci, sequi harum magnam provident dignissimos id voluptatum officia debitis corporis iusto animi magni rem quo quidem qui perferendis quibusdam beatae.`,
    amount: 1,
  },
];
